// Generated by tools/brand/optimise-premium.py. Prompts and provenance: premium-assets.json.
export const PREMIUM_ASSETS = {
  "manager.vera-focused": {
    "kind": "character",
    "variants": {
      "hero": {
        "src": "/art/premium/manager-vera-focused-hero.webp"
      },
      "card": {
        "src": "/art/premium/manager-vera-focused-card.webp"
      },
      "thumb": {
        "src": "/art/premium/manager-vera-focused-thumb.webp"
      }
    }
  },
  "manager.vera-happy": {
    "kind": "character",
    "variants": {
      "hero": {
        "src": "/art/premium/manager-vera-happy-hero.webp"
      },
      "card": {
        "src": "/art/premium/manager-vera-happy-card.webp"
      },
      "thumb": {
        "src": "/art/premium/manager-vera-happy-thumb.webp"
      }
    }
  },
  "manager.vera-disappointed": {
    "kind": "character",
    "variants": {
      "hero": {
        "src": "/art/premium/manager-vera-disappointed-hero.webp"
      },
      "card": {
        "src": "/art/premium/manager-vera-disappointed-card.webp"
      },
      "thumb": {
        "src": "/art/premium/manager-vera-disappointed-thumb.webp"
      }
    }
  },
  "manager.vera-celebrating": {
    "kind": "character",
    "variants": {
      "hero": {
        "src": "/art/premium/manager-vera-celebrating-hero.webp"
      },
      "card": {
        "src": "/art/premium/manager-vera-celebrating-card.webp"
      },
      "thumb": {
        "src": "/art/premium/manager-vera-celebrating-thumb.webp"
      }
    }
  },
  "manager.vera-neutral": {
    "kind": "character",
    "variants": {
      "hero": {
        "src": "/art/premium/manager-vera-neutral-hero.webp"
      },
      "card": {
        "src": "/art/premium/manager-vera-neutral-card.webp"
      },
      "thumb": {
        "src": "/art/premium/manager-vera-neutral-thumb.webp"
      }
    }
  },
  "environment.scouting-office": {
    "kind": "environment",
    "variants": {
      "hero": {
        "src": "/art/premium/scouting-office-hero.webp"
      },
      "card": {
        "src": "/art/premium/scouting-office-card.webp"
      },
      "thumb": {
        "src": "/art/premium/scouting-office-thumb.webp"
      }
    }
  },
  "environment.boardroom": {
    "kind": "environment",
    "variants": {
      "hero": {
        "src": "/art/premium/boardroom-hero.webp"
      },
      "card": {
        "src": "/art/premium/boardroom-card.webp"
      },
      "thumb": {
        "src": "/art/premium/boardroom-thumb.webp"
      }
    }
  },
  "environment.transfer-stage": {
    "kind": "environment",
    "variants": {
      "hero": {
        "src": "/art/premium/transfer-stage-hero.webp"
      },
      "card": {
        "src": "/art/premium/transfer-stage-card.webp"
      },
      "thumb": {
        "src": "/art/premium/transfer-stage-thumb.webp"
      }
    }
  },
  "character.player-05": {
    "kind": "character",
    "variants": {
      "hero": {
        "src": "/art/premium/player-05-hero.webp"
      },
      "card": {
        "src": "/art/premium/player-05-card.webp"
      },
      "thumb": {
        "src": "/art/premium/player-05-thumb.webp"
      }
    }
  },
  "character.player-06": {
    "kind": "character",
    "variants": {
      "hero": {
        "src": "/art/premium/player-06-hero.webp"
      },
      "card": {
        "src": "/art/premium/player-06-card.webp"
      },
      "thumb": {
        "src": "/art/premium/player-06-thumb.webp"
      }
    }
  },
  "character.player-07": {
    "kind": "character",
    "variants": {
      "hero": {
        "src": "/art/premium/player-07-hero.webp"
      },
      "card": {
        "src": "/art/premium/player-07-card.webp"
      },
      "thumb": {
        "src": "/art/premium/player-07-thumb.webp"
      }
    }
  },
  "character.player-08": {
    "kind": "character",
    "variants": {
      "hero": {
        "src": "/art/premium/player-08-hero.webp"
      },
      "card": {
        "src": "/art/premium/player-08-card.webp"
      },
      "thumb": {
        "src": "/art/premium/player-08-thumb.webp"
      }
    }
  },
  "character.player-01": {
    "kind": "character",
    "variants": {
      "hero": {
        "src": "/art/premium/player-01-hero.webp"
      },
      "card": {
        "src": "/art/premium/player-01-card.webp"
      },
      "thumb": {
        "src": "/art/premium/player-01-thumb.webp"
      }
    }
  },
  "character.player-02": {
    "kind": "character",
    "variants": {
      "hero": {
        "src": "/art/premium/player-02-hero.webp"
      },
      "card": {
        "src": "/art/premium/player-02-card.webp"
      },
      "thumb": {
        "src": "/art/premium/player-02-thumb.webp"
      }
    }
  },
  "character.player-03": {
    "kind": "character",
    "variants": {
      "hero": {
        "src": "/art/premium/player-03-hero.webp"
      },
      "card": {
        "src": "/art/premium/player-03-card.webp"
      },
      "thumb": {
        "src": "/art/premium/player-03-thumb.webp"
      }
    }
  },
  "character.player-04": {
    "kind": "character",
    "variants": {
      "hero": {
        "src": "/art/premium/player-04-hero.webp"
      },
      "card": {
        "src": "/art/premium/player-04-card.webp"
      },
      "thumb": {
        "src": "/art/premium/player-04-thumb.webp"
      }
    }
  },
  "environment.dressing-room": {
    "kind": "environment",
    "variants": {
      "hero": {
        "src": "/art/premium/dressing-room-hero.webp"
      },
      "card": {
        "src": "/art/premium/dressing-room-card.webp"
      },
      "thumb": {
        "src": "/art/premium/dressing-room-thumb.webp"
      }
    }
  },
  "environment.training-ground": {
    "kind": "environment",
    "variants": {
      "hero": {
        "src": "/art/premium/training-ground-hero.webp"
      },
      "card": {
        "src": "/art/premium/training-ground-card.webp"
      },
      "thumb": {
        "src": "/art/premium/training-ground-thumb.webp"
      }
    }
  },
  "environment.tactics-room": {
    "kind": "environment",
    "variants": {
      "hero": {
        "src": "/art/premium/tactics-room-hero.webp"
      },
      "card": {
        "src": "/art/premium/tactics-room-card.webp"
      },
      "thumb": {
        "src": "/art/premium/tactics-room-thumb.webp"
      }
    }
  },
  "environment.office": {
    "kind": "environment",
    "variants": {
      "hero": {
        "src": "/art/premium/office-hero.webp"
      },
      "card": {
        "src": "/art/premium/office-card.webp"
      },
      "thumb": {
        "src": "/art/premium/office-thumb.webp"
      }
    }
  },
  "manager.neutral": {
    "kind": "character",
    "variants": {
      "hero": {
        "src": "/art/premium/manager-neutral-hero.webp"
      },
      "card": {
        "src": "/art/premium/manager-neutral-card.webp"
      },
      "thumb": {
        "src": "/art/premium/manager-neutral-thumb.webp"
      }
    }
  },
  "object.tactics-tablet": {
    "kind": "object",
    "variants": {
      "hero": {
        "src": "/art/premium/tactics-tablet-hero.webp"
      },
      "card": {
        "src": "/art/premium/tactics-tablet-card.webp"
      },
      "thumb": {
        "src": "/art/premium/tactics-tablet-thumb.webp"
      }
    }
  },
  "object.training-cones": {
    "kind": "object",
    "variants": {
      "hero": {
        "src": "/art/premium/training-cones-hero.webp"
      },
      "card": {
        "src": "/art/premium/training-cones-card.webp"
      },
      "thumb": {
        "src": "/art/premium/training-cones-thumb.webp"
      }
    }
  },
  "object.scout-binoculars": {
    "kind": "object",
    "variants": {
      "hero": {
        "src": "/art/premium/scout-binoculars-hero.webp"
      },
      "card": {
        "src": "/art/premium/scout-binoculars-card.webp"
      },
      "thumb": {
        "src": "/art/premium/scout-binoculars-thumb.webp"
      }
    }
  },
  "environment.stadium-day": {
    "kind": "environment",
    "variants": {
      "hero": {
        "src": "/art/premium/environment-stadium-day-hero.webp"
      },
      "card": {
        "src": "/art/premium/environment-stadium-day-card.webp"
      },
      "thumb": {
        "src": "/art/premium/environment-stadium-day-thumb.webp"
      }
    }
  },
  "environment.stadium-night": {
    "kind": "environment",
    "variants": {
      "hero": {
        "src": "/art/premium/environment-stadium-night-hero.webp"
      },
      "card": {
        "src": "/art/premium/environment-stadium-night-card.webp"
      },
      "thumb": {
        "src": "/art/premium/environment-stadium-night-thumb.webp"
      }
    }
  },
  "environment.tunnel": {
    "kind": "environment",
    "variants": {
      "hero": {
        "src": "/art/premium/environment-tunnel-hero.webp"
      },
      "card": {
        "src": "/art/premium/environment-tunnel-card.webp"
      },
      "thumb": {
        "src": "/art/premium/environment-tunnel-thumb.webp"
      }
    }
  },
  "environment.academy": {
    "kind": "environment",
    "variants": {
      "hero": {
        "src": "/art/premium/environment-academy-hero.webp"
      },
      "card": {
        "src": "/art/premium/environment-academy-card.webp"
      },
      "thumb": {
        "src": "/art/premium/environment-academy-thumb.webp"
      }
    }
  },
  "environment.fan-zone": {
    "kind": "environment",
    "variants": {
      "hero": {
        "src": "/art/premium/environment-fan-zone-hero.webp"
      },
      "card": {
        "src": "/art/premium/environment-fan-zone-card.webp"
      },
      "thumb": {
        "src": "/art/premium/environment-fan-zone-thumb.webp"
      }
    }
  },
  "environment.media-studio": {
    "kind": "environment",
    "variants": {
      "hero": {
        "src": "/art/premium/environment-media-studio-hero.webp"
      },
      "card": {
        "src": "/art/premium/environment-media-studio-card.webp"
      },
      "thumb": {
        "src": "/art/premium/environment-media-studio-thumb.webp"
      }
    }
  },
  "environment.medical": {
    "kind": "environment",
    "variants": {
      "hero": {
        "src": "/art/premium/environment-medical-hero.webp"
      },
      "card": {
        "src": "/art/premium/environment-medical-card.webp"
      },
      "thumb": {
        "src": "/art/premium/environment-medical-thumb.webp"
      }
    }
  },
  "environment.trophy-room": {
    "kind": "environment",
    "variants": {
      "hero": {
        "src": "/art/premium/environment-trophy-room-hero.webp"
      },
      "card": {
        "src": "/art/premium/environment-trophy-room-card.webp"
      },
      "thumb": {
        "src": "/art/premium/environment-trophy-room-thumb.webp"
      }
    }
  },
  "character.player-09": {
    "kind": "character",
    "variants": {
      "hero": {
        "src": "/art/premium/player-09-hero.webp"
      },
      "card": {
        "src": "/art/premium/player-09-card.webp"
      },
      "thumb": {
        "src": "/art/premium/player-09-thumb.webp"
      }
    }
  },
  "character.player-10": {
    "kind": "character",
    "variants": {
      "hero": {
        "src": "/art/premium/player-10-hero.webp"
      },
      "card": {
        "src": "/art/premium/player-10-card.webp"
      },
      "thumb": {
        "src": "/art/premium/player-10-thumb.webp"
      }
    }
  },
  "character.player-11": {
    "kind": "character",
    "variants": {
      "hero": {
        "src": "/art/premium/player-11-hero.webp"
      },
      "card": {
        "src": "/art/premium/player-11-card.webp"
      },
      "thumb": {
        "src": "/art/premium/player-11-thumb.webp"
      }
    }
  },
  "character.player-12": {
    "kind": "character",
    "variants": {
      "hero": {
        "src": "/art/premium/player-12-hero.webp"
      },
      "card": {
        "src": "/art/premium/player-12-card.webp"
      },
      "thumb": {
        "src": "/art/premium/player-12-thumb.webp"
      }
    }
  },
  "character.player-13": {
    "kind": "character",
    "variants": {
      "hero": {
        "src": "/art/premium/player-13-hero.webp"
      },
      "card": {
        "src": "/art/premium/player-13-card.webp"
      },
      "thumb": {
        "src": "/art/premium/player-13-thumb.webp"
      }
    }
  },
  "character.player-14": {
    "kind": "character",
    "variants": {
      "hero": {
        "src": "/art/premium/player-14-hero.webp"
      },
      "card": {
        "src": "/art/premium/player-14-card.webp"
      },
      "thumb": {
        "src": "/art/premium/player-14-thumb.webp"
      }
    }
  },
  "character.player-15": {
    "kind": "character",
    "variants": {
      "hero": {
        "src": "/art/premium/player-15-hero.webp"
      },
      "card": {
        "src": "/art/premium/player-15-card.webp"
      },
      "thumb": {
        "src": "/art/premium/player-15-thumb.webp"
      }
    }
  },
  "character.player-16": {
    "kind": "character",
    "variants": {
      "hero": {
        "src": "/art/premium/player-16-hero.webp"
      },
      "card": {
        "src": "/art/premium/player-16-card.webp"
      },
      "thumb": {
        "src": "/art/premium/player-16-thumb.webp"
      }
    }
  },
  "character.player-17": {
    "kind": "character",
    "variants": {
      "hero": {
        "src": "/art/premium/player-17-hero.webp"
      },
      "card": {
        "src": "/art/premium/player-17-card.webp"
      },
      "thumb": {
        "src": "/art/premium/player-17-thumb.webp"
      }
    }
  },
  "character.player-18": {
    "kind": "character",
    "variants": {
      "hero": {
        "src": "/art/premium/player-18-hero.webp"
      },
      "card": {
        "src": "/art/premium/player-18-card.webp"
      },
      "thumb": {
        "src": "/art/premium/player-18-thumb.webp"
      }
    }
  },
  "character.player-19": {
    "kind": "character",
    "variants": {
      "hero": {
        "src": "/art/premium/player-19-hero.webp"
      },
      "card": {
        "src": "/art/premium/player-19-card.webp"
      },
      "thumb": {
        "src": "/art/premium/player-19-thumb.webp"
      }
    }
  },
  "character.player-20": {
    "kind": "character",
    "variants": {
      "hero": {
        "src": "/art/premium/player-20-hero.webp"
      },
      "card": {
        "src": "/art/premium/player-20-card.webp"
      },
      "thumb": {
        "src": "/art/premium/player-20-thumb.webp"
      }
    }
  },
  "character.player-21": {
    "kind": "character",
    "variants": {
      "hero": {
        "src": "/art/premium/player-21-hero.webp"
      },
      "card": {
        "src": "/art/premium/player-21-card.webp"
      },
      "thumb": {
        "src": "/art/premium/player-21-thumb.webp"
      }
    }
  },
  "character.player-22": {
    "kind": "character",
    "variants": {
      "hero": {
        "src": "/art/premium/player-22-hero.webp"
      },
      "card": {
        "src": "/art/premium/player-22-card.webp"
      },
      "thumb": {
        "src": "/art/premium/player-22-thumb.webp"
      }
    }
  },
  "character.player-23": {
    "kind": "character",
    "variants": {
      "hero": {
        "src": "/art/premium/player-23-hero.webp"
      },
      "card": {
        "src": "/art/premium/player-23-card.webp"
      },
      "thumb": {
        "src": "/art/premium/player-23-thumb.webp"
      }
    }
  },
  "character.player-24": {
    "kind": "character",
    "variants": {
      "hero": {
        "src": "/art/premium/player-24-hero.webp"
      },
      "card": {
        "src": "/art/premium/player-24-card.webp"
      },
      "thumb": {
        "src": "/art/premium/player-24-thumb.webp"
      }
    }
  },
  "character.staff-01": {
    "kind": "character",
    "variants": {
      "hero": {
        "src": "/art/premium/character-staff-01-hero.webp"
      },
      "card": {
        "src": "/art/premium/character-staff-01-card.webp"
      },
      "thumb": {
        "src": "/art/premium/character-staff-01-thumb.webp"
      }
    }
  },
  "character.staff-02": {
    "kind": "character",
    "variants": {
      "hero": {
        "src": "/art/premium/character-staff-02-hero.webp"
      },
      "card": {
        "src": "/art/premium/character-staff-02-card.webp"
      },
      "thumb": {
        "src": "/art/premium/character-staff-02-thumb.webp"
      }
    }
  },
  "character.staff-03": {
    "kind": "character",
    "variants": {
      "hero": {
        "src": "/art/premium/character-staff-03-hero.webp"
      },
      "card": {
        "src": "/art/premium/character-staff-03-card.webp"
      },
      "thumb": {
        "src": "/art/premium/character-staff-03-thumb.webp"
      }
    }
  },
  "character.staff-04": {
    "kind": "character",
    "variants": {
      "hero": {
        "src": "/art/premium/character-staff-04-hero.webp"
      },
      "card": {
        "src": "/art/premium/character-staff-04-card.webp"
      },
      "thumb": {
        "src": "/art/premium/character-staff-04-thumb.webp"
      }
    }
  },
  "character.staff-05": {
    "kind": "character",
    "variants": {
      "hero": {
        "src": "/art/premium/character-staff-05-hero.webp"
      },
      "card": {
        "src": "/art/premium/character-staff-05-card.webp"
      },
      "thumb": {
        "src": "/art/premium/character-staff-05-thumb.webp"
      }
    }
  },
  "character.staff-06": {
    "kind": "character",
    "variants": {
      "hero": {
        "src": "/art/premium/character-staff-06-hero.webp"
      },
      "card": {
        "src": "/art/premium/character-staff-06-card.webp"
      },
      "thumb": {
        "src": "/art/premium/character-staff-06-thumb.webp"
      }
    }
  },
  "character.staff-07": {
    "kind": "character",
    "variants": {
      "hero": {
        "src": "/art/premium/character-staff-07-hero.webp"
      },
      "card": {
        "src": "/art/premium/character-staff-07-card.webp"
      },
      "thumb": {
        "src": "/art/premium/character-staff-07-thumb.webp"
      }
    }
  },
  "character.staff-08": {
    "kind": "character",
    "variants": {
      "hero": {
        "src": "/art/premium/character-staff-08-hero.webp"
      },
      "card": {
        "src": "/art/premium/character-staff-08-card.webp"
      },
      "thumb": {
        "src": "/art/premium/character-staff-08-thumb.webp"
      }
    }
  },
  "crest.aurelia": {
    "kind": "crest",
    "variants": {
      "hero": {
        "src": "/art/premium/crest-aurelia-hero.webp"
      },
      "card": {
        "src": "/art/premium/crest-aurelia-card.webp"
      },
      "thumb": {
        "src": "/art/premium/crest-aurelia-thumb.webp"
      }
    }
  },
  "crest.cinderwick": {
    "kind": "crest",
    "variants": {
      "hero": {
        "src": "/art/premium/crest-cinderwick-hero.webp"
      },
      "card": {
        "src": "/art/premium/crest-cinderwick-card.webp"
      },
      "thumb": {
        "src": "/art/premium/crest-cinderwick-thumb.webp"
      }
    }
  },
  "crest.coppervale": {
    "kind": "crest",
    "variants": {
      "hero": {
        "src": "/art/premium/crest-coppervale-hero.webp"
      },
      "card": {
        "src": "/art/premium/crest-coppervale-card.webp"
      },
      "thumb": {
        "src": "/art/premium/crest-coppervale-thumb.webp"
      }
    }
  },
  "crest.duskford": {
    "kind": "crest",
    "variants": {
      "hero": {
        "src": "/art/premium/crest-duskford-hero.webp"
      },
      "card": {
        "src": "/art/premium/crest-duskford-card.webp"
      },
      "thumb": {
        "src": "/art/premium/crest-duskford-thumb.webp"
      }
    }
  },
  "crest.ember": {
    "kind": "crest",
    "variants": {
      "hero": {
        "src": "/art/premium/crest-ember-hero.webp"
      },
      "card": {
        "src": "/art/premium/crest-ember-card.webp"
      },
      "thumb": {
        "src": "/art/premium/crest-ember-thumb.webp"
      }
    }
  },
  "crest.ironhollow": {
    "kind": "crest",
    "variants": {
      "hero": {
        "src": "/art/premium/crest-ironhollow-hero.webp"
      },
      "card": {
        "src": "/art/premium/crest-ironhollow-card.webp"
      },
      "thumb": {
        "src": "/art/premium/crest-ironhollow-thumb.webp"
      }
    }
  },
  "crest.larkspur": {
    "kind": "crest",
    "variants": {
      "hero": {
        "src": "/art/premium/crest-larkspur-hero.webp"
      },
      "card": {
        "src": "/art/premium/crest-larkspur-card.webp"
      },
      "thumb": {
        "src": "/art/premium/crest-larkspur-thumb.webp"
      }
    }
  },
  "crest.marrowgate": {
    "kind": "crest",
    "variants": {
      "hero": {
        "src": "/art/premium/crest-marrowgate-hero.webp"
      },
      "card": {
        "src": "/art/premium/crest-marrowgate-card.webp"
      },
      "thumb": {
        "src": "/art/premium/crest-marrowgate-thumb.webp"
      }
    }
  },
  "crest.mossbank": {
    "kind": "crest",
    "variants": {
      "hero": {
        "src": "/art/premium/crest-mossbank-hero.webp"
      },
      "card": {
        "src": "/art/premium/crest-mossbank-card.webp"
      },
      "thumb": {
        "src": "/art/premium/crest-mossbank-thumb.webp"
      }
    }
  },
  "crest.neon-row": {
    "kind": "crest",
    "variants": {
      "hero": {
        "src": "/art/premium/crest-neon-row-hero.webp"
      },
      "card": {
        "src": "/art/premium/crest-neon-row-card.webp"
      },
      "thumb": {
        "src": "/art/premium/crest-neon-row-thumb.webp"
      }
    }
  },
  "crest.northglass": {
    "kind": "crest",
    "variants": {
      "hero": {
        "src": "/art/premium/crest-northglass-hero.webp"
      },
      "card": {
        "src": "/art/premium/crest-northglass-card.webp"
      },
      "thumb": {
        "src": "/art/premium/crest-northglass-thumb.webp"
      }
    }
  },
  "crest.redmere": {
    "kind": "crest",
    "variants": {
      "hero": {
        "src": "/art/premium/crest-redmere-hero.webp"
      },
      "card": {
        "src": "/art/premium/crest-redmere-card.webp"
      },
      "thumb": {
        "src": "/art/premium/crest-redmere-thumb.webp"
      }
    }
  },
  "crest.sable-coast": {
    "kind": "crest",
    "variants": {
      "hero": {
        "src": "/art/premium/crest-sable-coast-hero.webp"
      },
      "card": {
        "src": "/art/premium/crest-sable-coast-card.webp"
      },
      "thumb": {
        "src": "/art/premium/crest-sable-coast-thumb.webp"
      }
    }
  },
  "crest.saltpine": {
    "kind": "crest",
    "variants": {
      "hero": {
        "src": "/art/premium/crest-saltpine-hero.webp"
      },
      "card": {
        "src": "/art/premium/crest-saltpine-card.webp"
      },
      "thumb": {
        "src": "/art/premium/crest-saltpine-thumb.webp"
      }
    }
  },
  "crest.vantage": {
    "kind": "crest",
    "variants": {
      "hero": {
        "src": "/art/premium/crest-vantage-hero.webp"
      },
      "card": {
        "src": "/art/premium/crest-vantage-card.webp"
      },
      "thumb": {
        "src": "/art/premium/crest-vantage-thumb.webp"
      }
    }
  },
  "crest.verrow": {
    "kind": "crest",
    "variants": {
      "hero": {
        "src": "/art/premium/crest-verrow-hero.webp"
      },
      "card": {
        "src": "/art/premium/crest-verrow-card.webp"
      },
      "thumb": {
        "src": "/art/premium/crest-verrow-thumb.webp"
      }
    }
  },
  "kit.away": {
    "kind": "kit",
    "variants": {
      "hero": {
        "src": "/art/premium/kit-away-hero.webp"
      },
      "card": {
        "src": "/art/premium/kit-away-card.webp"
      },
      "thumb": {
        "src": "/art/premium/kit-away-thumb.webp"
      }
    }
  },
  "kit.goalkeeper": {
    "kind": "kit",
    "variants": {
      "hero": {
        "src": "/art/premium/kit-goalkeeper-hero.webp"
      },
      "card": {
        "src": "/art/premium/kit-goalkeeper-card.webp"
      },
      "thumb": {
        "src": "/art/premium/kit-goalkeeper-thumb.webp"
      }
    }
  },
  "kit.home": {
    "kind": "kit",
    "variants": {
      "hero": {
        "src": "/art/premium/kit-home-hero.webp"
      },
      "card": {
        "src": "/art/premium/kit-home-card.webp"
      },
      "thumb": {
        "src": "/art/premium/kit-home-thumb.webp"
      }
    }
  },
  "kit.training": {
    "kind": "kit",
    "variants": {
      "hero": {
        "src": "/art/premium/kit-training-hero.webp"
      },
      "card": {
        "src": "/art/premium/kit-training-card.webp"
      },
      "thumb": {
        "src": "/art/premium/kit-training-thumb.webp"
      }
    }
  },
  "trophy.boot": {
    "kind": "trophy",
    "variants": {
      "hero": {
        "src": "/art/premium/trophy-boot-hero.webp"
      },
      "card": {
        "src": "/art/premium/trophy-boot-card.webp"
      },
      "thumb": {
        "src": "/art/premium/trophy-boot-thumb.webp"
      }
    }
  },
  "trophy.cup": {
    "kind": "trophy",
    "variants": {
      "hero": {
        "src": "/art/premium/trophy-cup-hero.webp"
      },
      "card": {
        "src": "/art/premium/trophy-cup-card.webp"
      },
      "thumb": {
        "src": "/art/premium/trophy-cup-thumb.webp"
      }
    }
  },
  "trophy.league": {
    "kind": "trophy",
    "variants": {
      "hero": {
        "src": "/art/premium/trophy-league-hero.webp"
      },
      "card": {
        "src": "/art/premium/trophy-league-card.webp"
      },
      "thumb": {
        "src": "/art/premium/trophy-league-thumb.webp"
      }
    }
  },
  "trophy.superCup": {
    "kind": "trophy",
    "variants": {
      "hero": {
        "src": "/art/premium/trophy-superCup-hero.webp"
      },
      "card": {
        "src": "/art/premium/trophy-superCup-card.webp"
      },
      "thumb": {
        "src": "/art/premium/trophy-superCup-thumb.webp"
      }
    }
  },
  "object.analytics-tablet": {
    "kind": "object",
    "variants": {
      "hero": {
        "src": "/art/premium/object-analytics-tablet-hero.webp"
      },
      "card": {
        "src": "/art/premium/object-analytics-tablet-card.webp"
      },
      "thumb": {
        "src": "/art/premium/object-analytics-tablet-thumb.webp"
      }
    }
  },
  "object.boots-elite": {
    "kind": "object",
    "variants": {
      "hero": {
        "src": "/art/premium/object-boots-elite-hero.webp"
      },
      "card": {
        "src": "/art/premium/object-boots-elite-card.webp"
      },
      "thumb": {
        "src": "/art/premium/object-boots-elite-thumb.webp"
      }
    }
  },
  "object.boots-training": {
    "kind": "object",
    "variants": {
      "hero": {
        "src": "/art/premium/object-boots-training-hero.webp"
      },
      "card": {
        "src": "/art/premium/object-boots-training-card.webp"
      },
      "thumb": {
        "src": "/art/premium/object-boots-training-thumb.webp"
      }
    }
  },
  "object.club-bus": {
    "kind": "object",
    "variants": {
      "hero": {
        "src": "/art/premium/object-club-bus-hero.webp"
      },
      "card": {
        "src": "/art/premium/object-club-bus-card.webp"
      },
      "thumb": {
        "src": "/art/premium/object-club-bus-thumb.webp"
      }
    }
  },
  "object.club-mug": {
    "kind": "object",
    "variants": {
      "hero": {
        "src": "/art/premium/object-club-mug-hero.webp"
      },
      "card": {
        "src": "/art/premium/object-club-mug-card.webp"
      },
      "thumb": {
        "src": "/art/premium/object-club-mug-thumb.webp"
      }
    }
  },
  "object.creator-camera": {
    "kind": "object",
    "variants": {
      "hero": {
        "src": "/art/premium/object-creator-camera-hero.webp"
      },
      "card": {
        "src": "/art/premium/object-creator-camera-card.webp"
      },
      "thumb": {
        "src": "/art/premium/object-creator-camera-thumb.webp"
      }
    }
  },
  "object.floodlight": {
    "kind": "object",
    "variants": {
      "hero": {
        "src": "/art/premium/object-floodlight-hero.webp"
      },
      "card": {
        "src": "/art/premium/object-floodlight-card.webp"
      },
      "thumb": {
        "src": "/art/premium/object-floodlight-thumb.webp"
      }
    }
  },
  "object.football-elite": {
    "kind": "object",
    "variants": {
      "hero": {
        "src": "/art/premium/object-football-elite-hero.webp"
      },
      "card": {
        "src": "/art/premium/object-football-elite-card.webp"
      },
      "thumb": {
        "src": "/art/premium/object-football-elite-thumb.webp"
      }
    }
  },
  "object.football-training": {
    "kind": "object",
    "variants": {
      "hero": {
        "src": "/art/premium/object-football-training-hero.webp"
      },
      "card": {
        "src": "/art/premium/object-football-training-card.webp"
      },
      "thumb": {
        "src": "/art/premium/object-football-training-thumb.webp"
      }
    }
  },
  "object.hurdles": {
    "kind": "object",
    "variants": {
      "hero": {
        "src": "/art/premium/object-hurdles-hero.webp"
      },
      "card": {
        "src": "/art/premium/object-hurdles-card.webp"
      },
      "thumb": {
        "src": "/art/premium/object-hurdles-thumb.webp"
      }
    }
  },
  "object.kit-mannequins": {
    "kind": "object",
    "variants": {
      "hero": {
        "src": "/art/premium/object-kit-mannequins-hero.webp"
      },
      "card": {
        "src": "/art/premium/object-kit-mannequins-card.webp"
      },
      "thumb": {
        "src": "/art/premium/object-kit-mannequins-thumb.webp"
      }
    }
  },
  "object.magnetic-board": {
    "kind": "object",
    "variants": {
      "hero": {
        "src": "/art/premium/object-magnetic-board-hero.webp"
      },
      "card": {
        "src": "/art/premium/object-magnetic-board-card.webp"
      },
      "thumb": {
        "src": "/art/premium/object-magnetic-board-thumb.webp"
      }
    }
  },
  "object.manager-clipboard": {
    "kind": "object",
    "variants": {
      "hero": {
        "src": "/art/premium/object-manager-clipboard-hero.webp"
      },
      "card": {
        "src": "/art/premium/object-manager-clipboard-card.webp"
      },
      "thumb": {
        "src": "/art/premium/object-manager-clipboard-thumb.webp"
      }
    }
  },
  "object.manager-notebook": {
    "kind": "object",
    "variants": {
      "hero": {
        "src": "/art/premium/object-manager-notebook-hero.webp"
      },
      "card": {
        "src": "/art/premium/object-manager-notebook-card.webp"
      },
      "thumb": {
        "src": "/art/premium/object-manager-notebook-thumb.webp"
      }
    }
  },
  "object.mannequin-wall": {
    "kind": "object",
    "variants": {
      "hero": {
        "src": "/art/premium/object-mannequin-wall-hero.webp"
      },
      "card": {
        "src": "/art/premium/object-mannequin-wall-card.webp"
      },
      "thumb": {
        "src": "/art/premium/object-mannequin-wall-thumb.webp"
      }
    }
  },
  "object.medical-bag": {
    "kind": "object",
    "variants": {
      "hero": {
        "src": "/art/premium/object-medical-bag-hero.webp"
      },
      "card": {
        "src": "/art/premium/object-medical-bag-card.webp"
      },
      "thumb": {
        "src": "/art/premium/object-medical-bag-thumb.webp"
      }
    }
  },
  "object.press-podium": {
    "kind": "object",
    "variants": {
      "hero": {
        "src": "/art/premium/object-press-podium-hero.webp"
      },
      "card": {
        "src": "/art/premium/object-press-podium-card.webp"
      },
      "thumb": {
        "src": "/art/premium/object-press-podium-thumb.webp"
      }
    }
  },
  "object.report-folder": {
    "kind": "object",
    "variants": {
      "hero": {
        "src": "/art/premium/object-report-folder-hero.webp"
      },
      "card": {
        "src": "/art/premium/object-report-folder-card.webp"
      },
      "thumb": {
        "src": "/art/premium/object-report-folder-thumb.webp"
      }
    }
  },
  "object.stadium-seat": {
    "kind": "object",
    "variants": {
      "hero": {
        "src": "/art/premium/object-stadium-seat-hero.webp"
      },
      "card": {
        "src": "/art/premium/object-stadium-seat-card.webp"
      },
      "thumb": {
        "src": "/art/premium/object-stadium-seat-thumb.webp"
      }
    }
  },
  "object.streaming-desk": {
    "kind": "object",
    "variants": {
      "hero": {
        "src": "/art/premium/object-streaming-desk-hero.webp"
      },
      "card": {
        "src": "/art/premium/object-streaming-desk-card.webp"
      },
      "thumb": {
        "src": "/art/premium/object-streaming-desk-thumb.webp"
      }
    }
  },
  "object.training-bibs": {
    "kind": "object",
    "variants": {
      "hero": {
        "src": "/art/premium/object-training-bibs-hero.webp"
      },
      "card": {
        "src": "/art/premium/object-training-bibs-card.webp"
      },
      "thumb": {
        "src": "/art/premium/object-training-bibs-thumb.webp"
      }
    }
  },
  "object.treatment-table": {
    "kind": "object",
    "variants": {
      "hero": {
        "src": "/art/premium/object-treatment-table-hero.webp"
      },
      "card": {
        "src": "/art/premium/object-treatment-table-card.webp"
      },
      "thumb": {
        "src": "/art/premium/object-treatment-table-thumb.webp"
      }
    }
  },
  "object.turnstile-ticket": {
    "kind": "object",
    "variants": {
      "hero": {
        "src": "/art/premium/object-turnstile-ticket-hero.webp"
      },
      "card": {
        "src": "/art/premium/object-turnstile-ticket-card.webp"
      },
      "thumb": {
        "src": "/art/premium/object-turnstile-ticket-thumb.webp"
      }
    }
  },
  "object.whistle": {
    "kind": "object",
    "variants": {
      "hero": {
        "src": "/art/premium/object-whistle-hero.webp"
      },
      "card": {
        "src": "/art/premium/object-whistle-card.webp"
      },
      "thumb": {
        "src": "/art/premium/object-whistle-thumb.webp"
      }
    }
  },
  "story.defeat": {
    "kind": "story",
    "variants": {
      "hero": {
        "src": "/art/premium/story-defeat-hero.webp"
      },
      "card": {
        "src": "/art/premium/story-defeat-card.webp"
      },
      "thumb": {
        "src": "/art/premium/story-defeat-thumb.webp"
      }
    }
  },
  "story.injury": {
    "kind": "story",
    "variants": {
      "hero": {
        "src": "/art/premium/story-injury-hero.webp"
      },
      "card": {
        "src": "/art/premium/story-injury-card.webp"
      },
      "thumb": {
        "src": "/art/premium/story-injury-thumb.webp"
      }
    }
  },
  "story.transfer": {
    "kind": "story",
    "variants": {
      "hero": {
        "src": "/art/premium/story-transfer-hero.webp"
      },
      "card": {
        "src": "/art/premium/story-transfer-card.webp"
      },
      "thumb": {
        "src": "/art/premium/story-transfer-thumb.webp"
      }
    }
  },
  "story.victory": {
    "kind": "story",
    "variants": {
      "hero": {
        "src": "/art/premium/story-victory-hero.webp"
      },
      "card": {
        "src": "/art/premium/story-victory-card.webp"
      },
      "thumb": {
        "src": "/art/premium/story-victory-thumb.webp"
      }
    }
  },
  "trophy.creator": {
    "kind": "trophy",
    "variants": {
      "hero": {
        "src": "/art/premium/trophy-creator-hero.webp"
      },
      "card": {
        "src": "/art/premium/trophy-creator-card.webp"
      },
      "thumb": {
        "src": "/art/premium/trophy-creator-thumb.webp"
      }
    }
  },
  "trophy.legacy": {
    "kind": "trophy",
    "variants": {
      "hero": {
        "src": "/art/premium/trophy-legacy-hero.webp"
      },
      "card": {
        "src": "/art/premium/trophy-legacy-card.webp"
      },
      "thumb": {
        "src": "/art/premium/trophy-legacy-thumb.webp"
      }
    }
  },
  "trophy.medal": {
    "kind": "trophy",
    "variants": {
      "hero": {
        "src": "/art/premium/trophy-medal-hero.webp"
      },
      "card": {
        "src": "/art/premium/trophy-medal-card.webp"
      },
      "thumb": {
        "src": "/art/premium/trophy-medal-thumb.webp"
      }
    }
  },
  "trophy.youth": {
    "kind": "trophy",
    "variants": {
      "hero": {
        "src": "/art/premium/trophy-youth-hero.webp"
      },
      "card": {
        "src": "/art/premium/trophy-youth-card.webp"
      },
      "thumb": {
        "src": "/art/premium/trophy-youth-thumb.webp"
      }
    }
  },
  "story.training": {
    "kind": "story",
    "variants": {
      "hero": {
        "src": "/art/premium/story-training-hero.webp"
      },
      "card": {
        "src": "/art/premium/story-training-card.webp"
      },
      "thumb": {
        "src": "/art/premium/story-training-thumb.webp"
      }
    }
  },
  "story.press": {
    "kind": "story",
    "variants": {
      "hero": {
        "src": "/art/premium/story-press-hero.webp"
      },
      "card": {
        "src": "/art/premium/story-press-card.webp"
      },
      "thumb": {
        "src": "/art/premium/story-press-thumb.webp"
      }
    }
  },
  "story.fans": {
    "kind": "story",
    "variants": {
      "hero": {
        "src": "/art/premium/story-fans-hero.webp"
      },
      "card": {
        "src": "/art/premium/story-fans-card.webp"
      },
      "thumb": {
        "src": "/art/premium/story-fans-thumb.webp"
      }
    }
  },
  "story.sponsorship": {
    "kind": "story",
    "variants": {
      "hero": {
        "src": "/art/premium/story-sponsorship-hero.webp"
      },
      "card": {
        "src": "/art/premium/story-sponsorship-card.webp"
      },
      "thumb": {
        "src": "/art/premium/story-sponsorship-thumb.webp"
      }
    }
  },
  "story.creator": {
    "kind": "story",
    "variants": {
      "hero": {
        "src": "/art/premium/story-creator-hero.webp"
      },
      "card": {
        "src": "/art/premium/story-creator-card.webp"
      },
      "thumb": {
        "src": "/art/premium/story-creator-thumb.webp"
      }
    }
  },
  "story.rivalry": {
    "kind": "story",
    "variants": {
      "hero": {
        "src": "/art/premium/story-rivalry-hero.webp"
      },
      "card": {
        "src": "/art/premium/story-rivalry-card.webp"
      },
      "thumb": {
        "src": "/art/premium/story-rivalry-thumb.webp"
      }
    }
  },
  "story.matchday": {
    "kind": "story",
    "variants": {
      "hero": {
        "src": "/art/premium/story-matchday-hero.webp"
      },
      "card": {
        "src": "/art/premium/story-matchday-card.webp"
      },
      "thumb": {
        "src": "/art/premium/story-matchday-thumb.webp"
      }
    }
  },
  "story.academy": {
    "kind": "story",
    "variants": {
      "hero": {
        "src": "/art/premium/story-academy-hero.webp"
      },
      "card": {
        "src": "/art/premium/story-academy-card.webp"
      },
      "thumb": {
        "src": "/art/premium/story-academy-thumb.webp"
      }
    }
  },
  "ambience.dusk-overcast": {
    "kind": "ambience",
    "variants": {
      "hero": {
        "src": "/art/premium/ambience-dusk-overcast-hero.webp"
      },
      "card": {
        "src": "/art/premium/ambience-dusk-overcast-card.webp"
      },
      "thumb": {
        "src": "/art/premium/ambience-dusk-overcast-thumb.webp"
      }
    }
  },
  "ambience.night-fog": {
    "kind": "ambience",
    "variants": {
      "hero": {
        "src": "/art/premium/ambience-night-fog-hero.webp"
      },
      "card": {
        "src": "/art/premium/ambience-night-fog-card.webp"
      },
      "thumb": {
        "src": "/art/premium/ambience-night-fog-thumb.webp"
      }
    }
  },
  "ambience.day-snow": {
    "kind": "ambience",
    "variants": {
      "hero": {
        "src": "/art/premium/ambience-day-snow-hero.webp"
      },
      "card": {
        "src": "/art/premium/ambience-day-snow-card.webp"
      },
      "thumb": {
        "src": "/art/premium/ambience-day-snow-thumb.webp"
      }
    }
  },
  "ambience.dawn-clear": {
    "kind": "ambience",
    "variants": {
      "hero": {
        "src": "/art/premium/ambience-dawn-clear-hero.webp"
      },
      "card": {
        "src": "/art/premium/ambience-dawn-clear-card.webp"
      },
      "thumb": {
        "src": "/art/premium/ambience-dawn-clear-thumb.webp"
      }
    }
  },
  "ambience.day-clear": {
    "kind": "ambience",
    "variants": {
      "hero": {
        "src": "/art/premium/ambience-day-clear-hero.webp"
      },
      "card": {
        "src": "/art/premium/ambience-day-clear-card.webp"
      },
      "thumb": {
        "src": "/art/premium/ambience-day-clear-thumb.webp"
      }
    }
  },
  "ambience.night-clear": {
    "kind": "ambience",
    "variants": {
      "hero": {
        "src": "/art/premium/ambience-night-clear-hero.webp"
      },
      "card": {
        "src": "/art/premium/ambience-night-clear-card.webp"
      },
      "thumb": {
        "src": "/art/premium/ambience-night-clear-thumb.webp"
      }
    }
  },
  "ambience.day-rain": {
    "kind": "ambience",
    "variants": {
      "hero": {
        "src": "/art/premium/ambience-day-rain-hero.webp"
      },
      "card": {
        "src": "/art/premium/ambience-day-rain-card.webp"
      },
      "thumb": {
        "src": "/art/premium/ambience-day-rain-thumb.webp"
      }
    }
  },
  "ambience.night-rain": {
    "kind": "ambience",
    "variants": {
      "hero": {
        "src": "/art/premium/ambience-night-rain-hero.webp"
      },
      "card": {
        "src": "/art/premium/ambience-night-rain-card.webp"
      },
      "thumb": {
        "src": "/art/premium/ambience-night-rain-thumb.webp"
      }
    }
  },
  "environment.stadium-day-elite": {
    "kind": "environment",
    "variants": {
      "hero": {
        "src": "/art/premium/environment-stadium-day-elite-hero.webp"
      },
      "card": {
        "src": "/art/premium/environment-stadium-day-elite-card.webp"
      },
      "thumb": {
        "src": "/art/premium/environment-stadium-day-elite-thumb.webp"
      }
    }
  }
} as const;
export type AssetKey = keyof typeof PREMIUM_ASSETS;
