import type { ClubId, PlayerId } from '../core/brand';

/**
 * The match event stream.
 *
 * This is the single source of truth for everything that happens in a match.
 * The animated pitch, the broadcast view, commentary, analytics, the social
 * feed, the media engine, history and rewards are ALL derived from this array.
 * No renderer may invent an event, and no system may learn about a match by any
 * other route.
 */
export const MATCH_EVENT_TYPES = [
  'MATCH_START', 'KICK_OFF', 'POSSESSION_CHANGE', 'PASS', 'CARRY', 'CROSS',
  'SHOT', 'SAVE', 'GOAL', 'MISS', 'POST', 'BLOCK', 'TACKLE', 'INTERCEPTION',
  'FOUL', 'YELLOW_CARD', 'RED_CARD', 'PENALTY_AWARDED', 'PENALTY_SCORED',
  'PENALTY_MISSED', 'CORNER', 'FREE_KICK', 'OFFSIDE', 'INJURY', 'SUBSTITUTION',
  'TACTICAL_CHANGE', 'SPECIAL_RULE_START', 'SPECIAL_RULE_END', 'MOMENTUM_SHIFT',
  'CHANCE_CREATED', 'CREATOR_MOMENT', 'HALFTIME', 'PERIOD_START', 'PERIOD_END',
  'FULLTIME', 'DECISION_PROMPT', 'DECISION_RESOLVED', 'COMMENTARY',
] as const;
export type MatchEventType = (typeof MATCH_EVENT_TYPES)[number];

export type Side = 'home' | 'away';

export interface PitchPoint { readonly x: number; readonly y: number }

export interface MatchEvent {
  readonly id: string;
  readonly type: MatchEventType;
  /** Match minute (may exceed regulation during added time). */
  readonly minute: number;
  /** Simulation tick index, for exact ordering and renderer sync. */
  readonly tick: number;
  readonly side?: Side;
  readonly clubId?: ClubId;
  readonly playerId?: PlayerId;
  readonly secondaryPlayerId?: PlayerId;
  readonly at?: PitchPoint;
  readonly target?: PitchPoint;
  /** Expected-goals value; present on SHOT, GOAL, MISS, SAVE, CHANCE_CREATED. */
  readonly xg?: number;
  readonly homeScore: number;
  readonly awayScore: number;
  /** -1 (away dominant) .. +1 (home dominant) at the moment of the event. */
  readonly momentum: number;
  /** Human-readable line. Generated by the commentary layer, stored for replay. */
  readonly text: string;
  /** 1-5. Drives whether the UI interrupts, animates, or logs quietly. */
  readonly importance: 1 | 2 | 3 | 4 | 5;
  readonly detail?: Readonly<Record<string, string | number | boolean>>;
}

/** Per-tick positional snapshot consumed by the animated pitch renderer. */
export interface PitchFrame {
  readonly tick: number;
  readonly minute: number;
  readonly ball: PitchPoint;
  readonly ballHolder: PlayerId | null;
  readonly players: readonly PitchPlayerFrame[];
  readonly phase: PlayPhase;
}

export type PlayPhase =
  | 'BUILD_UP' | 'PROGRESSION' | 'FINAL_THIRD' | 'SHOT' | 'TRANSITION'
  | 'PRESS' | 'SET_PIECE' | 'RESTART' | 'CELEBRATION' | 'STOPPAGE';

export interface PitchPlayerFrame {
  readonly playerId: PlayerId;
  readonly side: Side;
  readonly x: number;
  readonly y: number;
  readonly hasBall: boolean;
  /** Drives the renderer's pose/emphasis without leaking sim internals. */
  readonly state: 'IDLE' | 'RUNNING' | 'PRESSING' | 'RECEIVING' | 'SHOOTING' | 'TACKLING' | 'CELEBRATING' | 'DOWN';
  readonly stamina: number;
}
