import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { advanceCycle, type GameState, type Objective } from '@cf/engine';
import assert from 'node:assert/strict';
const artifact = resolve(process.cwd(), '../../artifacts/redesign');
const browser = JSON.parse(readFileSync(resolve(artifact, 'signed-state.json'), 'utf8'));
const state: GameState = JSON.parse(browser.origins[0].localStorage.find((v: {name:string}) => v.name === 'cf.save.v1').value).state;
const event = state.pendingActionEvents?.find(e => e.type === 'PLAYER_SIGNED');
assert.ok(event && event.type === 'PLAYER_SIGNED');
const objective: Objective = { id: 'test-signing-provenance', title: 'Strengthen the squad', description: 'Sign two players', kind: 'SIGN_PLAYERS', target: 2, progress: 0, rewards: [], expiresCycle: null, status: 'ACTIVE', source: 'DYNAMIC', importance: 3 };
const first = advanceCycle({ ...state, objectives: { ...state.objectives, active: [...state.objectives.active, objective] } }, { now: 2000 });
assert.equal(first.state.objectives.active.find(o => o.id === objective.id)?.progress, 1);
assert.equal(first.state.pendingActionEvents?.length, 0);
assert.equal(first.state.eventLog.filter(e => e.id === event.id).length, 1);
const reactionPosts = first.posts.filter(p => p.relatedEventId === event.id);
const reactionStories = first.stories.filter(s => s.entities.some(e => e.id === event.payload.playerId));
assert.ok(reactionPosts.length + reactionStories.length > 0, 'Signing produced no event-backed world reaction');
const second = advanceCycle(first.state, { now: 3000 });
assert.equal(second.state.objectives.active.find(o => o.id === objective.id)?.progress, 1);
writeFileSync(resolve(artifact, 'completion-signing-consequences.json'), JSON.stringify({ objectiveProgress: 1, eventConsumedOnce: true, posts: reactionPosts.length, stories: reactionStories.length }, null, 2));
console.log('Real UI signing advances objective and world once.');
