import { CREATOR_ATTRIBUTE_KEYS, type CreatorAttributeKey } from '../../../creators/creator';
import type { CreatorTemplate } from '../../schema';

/**
 * The twenty-eight named creators of the base universe.
 *
 * The roster is weighted the way the real thing is: creators own and manage
 * clubs far more often than they play for them. Twelve of the twenty-eight are
 * club presidents, six are media, three are club personalities, three are
 * unaffiliated chaos, and only four actually play — and those four are treated
 * in the fiction as the exception that gets written about, not the norm.
 *
 * They are also deliberately not all likeable. A world where every creator is
 * charming produces no stories. Half of this roster exists to generate friction:
 * a president who briefs against his own manager, a pundit who has never once
 * enjoyed a football match, an analyst who publicly ranks the supporters.
 *
 * Every person here is invented. No name, handle, biography or persona refers
 * to, resembles or is decodable as any real creator, streamer or broadcaster.
 */

const ca = (
  partial: Partial<Record<CreatorAttributeKey, number>>,
): Record<string, number> =>
  Object.fromEntries(CREATOR_ATTRIBUTE_KEYS.map((k) => [k, partial[k] ?? 50]));

export const BASE_CREATORS: readonly CreatorTemplate[] = [
  /* ------------------------------------------------------------- GLOBAL */
  {
    id: 'creator_ruse_vandry',
    handle: 'ruse',
    displayName: 'Ruse Vandry',
    roles: ['OWNER', 'MANAGER'],
    tier: 'GLOBAL',
    followers: 21_400_000,
    attributes: ca({
      audience: 96, engagement: 78, charisma: 88, controversy: 84, brandValue: 93,
      loyalty: 34, leadership: 71, entertainment: 90, mediaAbility: 82,
      fanConversion: 66, commercialAppeal: 94,
    }),
    style: { tone: 'PROVOCATIVE', platforms: ['STREAM', 'SHORTFORM', 'LONGFORM'], postingFrequency: 6 },
    clubTemplateId: 'club_neon_row_fc',
    bio: 'Built a football club in eleven weeks to prove a point, then kept it because winning the argument turned out to be less fun than winning the league. Will announce a signing before the medical and blame you for the leak.',
    avatarSeed: 'ruse-vandry-01',
  },
  {
    id: 'creator_sunny_odhiambo',
    handle: 'sunnyside',
    displayName: 'Sunny Odhiambo',
    roles: ['INFLUENCER', 'PUNDIT'],
    tier: 'GLOBAL',
    followers: 15_200_000,
    attributes: ca({
      audience: 92, engagement: 84, charisma: 95, controversy: 38, brandValue: 86,
      loyalty: 62, leadership: 55, entertainment: 96, mediaAbility: 89,
      fanConversion: 58, commercialAppeal: 88,
    }),
    style: { tone: 'COMEDIC', platforms: ['SHORTFORM', 'STREAM', 'PODCAST'], postingFrequency: 8 },
    bio: 'Hosts the matchday block and has never once let a bad game stay a bad game. Neutral to the point of infuriating everyone: twelve sets of supporters are each convinced he is against them specifically.',
    avatarSeed: 'sunny-odhiambo-01',
  },
  {
    id: 'creator_bex_calloway',
    handle: 'bexplainsit',
    displayName: 'Bex Calloway',
    roles: ['PUNDIT', 'INFLUENCER'],
    tier: 'GLOBAL',
    followers: 12_800_000,
    attributes: ca({
      audience: 90, engagement: 71, charisma: 74, controversy: 30, brandValue: 84,
      loyalty: 70, leadership: 60, entertainment: 68, mediaAbility: 94,
      fanConversion: 52, commercialAppeal: 79,
    }),
    style: { tone: 'ANALYTICAL', platforms: ['LONGFORM', 'PODCAST', 'TEXT'], postingFrequency: 3 },
    bio: 'The only person in this league everyone believes. Explains a defensive shape in ninety seconds with a marker pen and no jokes, and has quietly ended two managerial careers by being calmly right on camera.',
    avatarSeed: 'bex-calloway-01',
  },

  /* -------------------------------------------------------------- MAJOR */
  {
    id: 'creator_nadia_veldman',
    handle: 'veldmanvs',
    displayName: 'Nadia Veldman',
    roles: ['OWNER'],
    tier: 'MAJOR',
    followers: 5_600_000,
    attributes: ca({
      audience: 82, engagement: 64, charisma: 80, controversy: 72, brandValue: 95,
      loyalty: 44, leadership: 66, entertainment: 74, mediaAbility: 77,
      fanConversion: 48, commercialAppeal: 97,
    }),
    style: { tone: 'PROVOCATIVE', platforms: ['SHORTFORM', 'TEXT'], postingFrequency: 3 },
    clubTemplateId: 'club_aurelia_sc',
    bio: 'Creative director first, club president second, and entirely unbothered that supporters can tell. Treats the squad like a collection and the league like a season — she has already shown next year\'s kit to people who do not care about football.',
    avatarSeed: 'nadia-veldman-01',
  },
  {
    id: 'creator_mo_ashbury',
    handle: 'emberninemo',
    displayName: 'Mo Ashbury',
    roles: ['OWNER', 'MANAGER'],
    tier: 'MAJOR',
    followers: 4_100_000,
    attributes: ca({
      audience: 79, engagement: 88, charisma: 84, controversy: 45, brandValue: 71,
      loyalty: 88, leadership: 78, entertainment: 86, mediaAbility: 69,
      fanConversion: 82, commercialAppeal: 70,
    }),
    style: { tone: 'HYPE', platforms: ['STREAM', 'SHORTFORM'], postingFrequency: 7 },
    clubTemplateId: 'club_ember_nine',
    bio: 'Bought a dead club, its badge and its debts, and has streamed every board meeting since — including the two he lost. Genuinely, exhaustingly sincere about it, which is why the old Emberfield supporters have grudgingly let him keep the name.',
    avatarSeed: 'mo-ashbury-01',
  },
  {
    id: 'creator_rem_bassey',
    handle: 'remontape',
    displayName: 'Rem Bassey',
    roles: ['PLAYER', 'INFLUENCER'],
    tier: 'MAJOR',
    followers: 3_300_000,
    attributes: ca({
      audience: 76, engagement: 82, charisma: 79, controversy: 61, brandValue: 74,
      loyalty: 51, leadership: 48, entertainment: 91, mediaAbility: 58,
      fanConversion: 71, commercialAppeal: 80,
    }),
    style: { tone: 'HYPE', platforms: ['SHORTFORM', 'STREAM'], postingFrequency: 9 },
    clubTemplateId: 'club_neon_row_fc',
    playerTemplateId: 'player_rem_bassey',
    bio: 'One of the four people in this league who both plays and posts, and by some distance the loudest. Films his own warm-up, celebrates to the camera before the ball crosses the line, and has been booked twice for it.',
    avatarSeed: 'rem-bassey-01',
  },
  {
    id: 'creator_ambrose_quill',
    handle: 'quillspeaks',
    displayName: 'Ambrose Quill',
    roles: ['OWNER', 'CLUB_PERSONALITY'],
    tier: 'MAJOR',
    followers: 2_900_000,
    attributes: ca({
      audience: 68, engagement: 55, charisma: 72, controversy: 77, brandValue: 81,
      loyalty: 92, leadership: 74, entertainment: 66, mediaAbility: 52,
      fanConversion: 44, commercialAppeal: 76,
    }),
    style: { tone: 'DRAMATIC', platforms: ['TEXT', 'LONGFORM'], postingFrequency: 2 },
    clubTemplateId: 'club_marrowgate_athletic',
    bio: 'The fourth Quill to run Marrowgate and the first to discover the internet, which happened at sixty-one when a clip of him calling a rival "a shop" went everywhere. Now posts nine-hundred-word statements at two in the morning and refuses to have them edited.',
    avatarSeed: 'ambrose-quill-01',
  },
  {
    id: 'creator_coco_panetta',
    handle: 'cocosbench',
    displayName: 'Coco Panetta',
    roles: ['OWNER', 'MANAGER'],
    tier: 'MAJOR',
    followers: 2_200_000,
    attributes: ca({
      audience: 71, engagement: 86, charisma: 90, controversy: 52, brandValue: 66,
      loyalty: 79, leadership: 82, entertainment: 94, mediaAbility: 80,
      fanConversion: 74, commercialAppeal: 68,
    }),
    style: { tone: 'COMEDIC', platforms: ['STREAM', 'SHORTFORM', 'PODCAST'], postingFrequency: 6 },
    clubTemplateId: 'club_larkspur_wolves',
    bio: 'Runs Larkspur on the stated principle that a nil-nil is a moral failure, and has the goal difference to prove she means it. Does her post-match reaction from the terrace with a pint, win or lose, and has apologised for exactly none of them.',
    avatarSeed: 'coco-panetta-01',
  },

  /* -------------------------------------------------------- ESTABLISHED */
  {
    id: 'creator_hollis_wray',
    handle: 'hollisonair',
    displayName: 'Hollis Wray',
    roles: ['PUNDIT'],
    tier: 'ESTABLISHED',
    followers: 1_400_000,
    attributes: ca({
      audience: 64, engagement: 60, charisma: 83, controversy: 58, brandValue: 62,
      loyalty: 66, leadership: 46, entertainment: 88, mediaAbility: 91,
      fanConversion: 40, commercialAppeal: 64,
    }),
    style: { tone: 'DRAMATIC', platforms: ['STREAM', 'LONGFORM'], postingFrequency: 4 },
    bio: 'Lead commentator, and a man who has never described a throw-in without implying that history is watching. Beloved, quotable, and completely incapable of using a small word where an enormous one is available.',
    avatarSeed: 'hollis-wray-01',
  },
  {
    id: 'creator_priya_chandra',
    handle: 'chandrachalkboard',
    displayName: 'Priya Chandra',
    roles: ['PUNDIT', 'INFLUENCER'],
    tier: 'ESTABLISHED',
    followers: 1_100_000,
    attributes: ca({
      audience: 62, engagement: 74, charisma: 61, controversy: 34, brandValue: 58,
      loyalty: 72, leadership: 54, entertainment: 56, mediaAbility: 86,
      fanConversion: 48, commercialAppeal: 60,
    }),
    style: { tone: 'ANALYTICAL', platforms: ['LONGFORM', 'TEXT'], postingFrequency: 2 },
    bio: 'Publishes a thirty-page tactical review the morning after every matchday and has been right about relegation four seasons running. Clubs quote her when she agrees with them and call her "a spreadsheet" when she does not.',
    avatarSeed: 'priya-chandra-01',
  },
  {
    id: 'creator_della_marsh',
    handle: 'dellamarsh',
    displayName: 'Della Marsh',
    roles: ['OWNER'],
    tier: 'ESTABLISHED',
    followers: 940_000,
    attributes: ca({
      audience: 58, engagement: 52, charisma: 48, controversy: 66, brandValue: 70,
      loyalty: 60, leadership: 76, entertainment: 40, mediaAbility: 64,
      fanConversion: 36, commercialAppeal: 72,
    }),
    style: { tone: 'ANALYTICAL', platforms: ['TEXT', 'LONGFORM'], postingFrequency: 2 },
    clubTemplateId: 'club_vantage_point_fc',
    bio: 'Left a trading desk to prove a football club could be run without sentiment, and is roughly seventy per cent of the way to proving it. Published a supporter-value model on the club site and took nine days to understand why that was a mistake.',
    avatarSeed: 'della-marsh-01',
  },
  {
    id: 'creator_kacper_wojcik',
    handle: 'kacpershoots',
    displayName: 'Kacper Wojcik',
    roles: ['PLAYER', 'INFLUENCER'],
    tier: 'ESTABLISHED',
    followers: 890_000,
    attributes: ca({
      audience: 56, engagement: 70, charisma: 66, controversy: 44, brandValue: 63,
      loyalty: 58, leadership: 52, entertainment: 78, mediaAbility: 50,
      fanConversion: 62, commercialAppeal: 74,
    }),
    style: { tone: 'HYPE', platforms: ['SHORTFORM'], postingFrequency: 7 },
    clubTemplateId: 'club_aurelia_sc',
    playerTemplateId: 'player_kacper_wojcik',
    bio: 'Signed by Aurelia as much for the follower count as the finishing, and has spent two seasons quietly making that look like a bargain. Posts nothing but goals, which has made him the least controversial famous person in the league.',
    avatarSeed: 'kacper-wojcik-01',
  },
  {
    id: 'creator_ivo_prentice',
    handle: 'prenticepresser',
    displayName: 'Ivo Prentice',
    roles: ['PUNDIT'],
    tier: 'ESTABLISHED',
    followers: 780_000,
    attributes: ca({
      audience: 54, engagement: 66, charisma: 58, controversy: 89, brandValue: 47,
      loyalty: 38, leadership: 44, entertainment: 72, mediaAbility: 76,
      fanConversion: 30, commercialAppeal: 41,
    }),
    style: { tone: 'PROVOCATIVE', platforms: ['PODCAST', 'SHORTFORM'], postingFrequency: 5 },
    bio: 'Managed for eleven years, was sacked from all of it, and has monetised the grievance beautifully. Opens every episode with "I will say what nobody else will" and then says the thing four other people already said on Sunday.',
    avatarSeed: 'ivo-prentice-01',
  },
  {
    id: 'creator_saffi_nakamura',
    handle: 'saffisunday',
    displayName: 'Saffi Nakamura',
    roles: ['OWNER', 'CLUB_PERSONALITY'],
    tier: 'ESTABLISHED',
    followers: 610_000,
    attributes: ca({
      audience: 52, engagement: 91, charisma: 77, controversy: 18, brandValue: 49,
      loyalty: 96, leadership: 85, entertainment: 64, mediaAbility: 70,
      fanConversion: 88, commercialAppeal: 46,
    }),
    style: { tone: 'WHOLESOME', platforms: ['STREAM', 'TEXT'], postingFrequency: 4 },
    clubTemplateId: 'club_redmere_republic',
    bio: 'Elected president of Redmere by eleven thousand members and answers to every one of them, which she treats as a feature. Reads out the accounts on stream once a month. It is not entertaining and it is the most-watched thing the club does.',
    avatarSeed: 'saffi-nakamura-01',
  },
  {
    id: 'creator_gus_torrance',
    handle: 'gustorrance',
    displayName: 'Gus Torrance',
    roles: ['CLUB_PERSONALITY'],
    tier: 'ESTABLISHED',
    followers: 520_000,
    attributes: ca({
      audience: 50, engagement: 84, charisma: 81, controversy: 22, brandValue: 44,
      loyalty: 97, leadership: 62, entertainment: 83, mediaAbility: 66,
      fanConversion: 79, commercialAppeal: 48,
    }),
    style: { tone: 'WHOLESOME', platforms: ['SHORTFORM', 'STREAM'], postingFrequency: 5 },
    clubTemplateId: 'club_ironhollow_forge',
    bio: 'Was the stadium announcer at Ironhollow for nineteen years before somebody uploaded him losing his mind over a ninetieth-minute clearance. Still does the announcing. Still loses his mind. Has refused three jobs that would have paid him properly.',
    avatarSeed: 'gus-torrance-01',
  },

  /* ------------------------------------------------------------- RISING */
  {
    id: 'creator_fen_duvall',
    handle: 'fenduvall',
    displayName: 'Fen Duvall',
    roles: ['PLAYER'],
    tier: 'RISING',
    followers: 380_000,
    attributes: ca({
      audience: 42, engagement: 88, charisma: 62, controversy: 40, brandValue: 55,
      loyalty: 74, leadership: 30, entertainment: 76, mediaAbility: 38,
      fanConversion: 68, commercialAppeal: 66,
    }),
    style: { tone: 'HYPE', platforms: ['SHORTFORM'], postingFrequency: 8 },
    clubTemplateId: 'club_duskford_rovers',
    playerTemplateId: 'player_fen_duvall',
    bio: 'Nineteen, from the Duskford academy, and the follower count is growing faster than the appearance count. Two of the biggest clubs in the league already follow him back, which everyone at Duskford has noticed and nobody will discuss.',
    avatarSeed: 'fen-duvall-01',
  },
  {
    id: 'creator_zaid_almeida',
    handle: 'zaidclips',
    displayName: 'Zaid Almeida',
    roles: ['INFLUENCER'],
    tier: 'RISING',
    followers: 310_000,
    attributes: ca({
      audience: 44, engagement: 79, charisma: 68, controversy: 63, brandValue: 38,
      loyalty: 26, leadership: 28, entertainment: 87, mediaAbility: 42,
      fanConversion: 34, commercialAppeal: 52,
    }),
    style: { tone: 'COMEDIC', platforms: ['SHORTFORM'], postingFrequency: 12 },
    bio: 'Owns no club, supports no club, and is in every clip you have seen from this league. Turns a defender\'s bad touch into four hundred thousand views by Tuesday and has been banned from two grounds for filming in the tunnel.',
    avatarSeed: 'zaid-almeida-01',
  },
  {
    id: 'creator_neve_halloran',
    handle: 'nevehalloran',
    displayName: 'Neve Halloran',
    roles: ['OWNER'],
    tier: 'RISING',
    followers: 240_000,
    attributes: ca({
      audience: 38, engagement: 82, charisma: 70, controversy: 20, brandValue: 44,
      loyalty: 90, leadership: 80, entertainment: 58, mediaAbility: 72,
      fanConversion: 76, commercialAppeal: 45,
    }),
    style: { tone: 'WHOLESOME', platforms: ['LONGFORM', 'TEXT'], postingFrequency: 3 },
    clubTemplateId: 'club_duskford_rovers',
    bio: 'Runs Duskford like a school she is proud of, which is charming right up to the week a bigger club comes for the sixteen-year-old. Has cried on camera twice, both times about a sale, and it did more for the club than any signing.',
    avatarSeed: 'neve-halloran-01',
  },
  {
    id: 'creator_mira_sekulic',
    handle: 'mirasekulic',
    displayName: 'Mira Sekulic',
    roles: ['PUNDIT'],
    tier: 'RISING',
    followers: 205_000,
    attributes: ca({
      audience: 36, engagement: 76, charisma: 52, controversy: 86, brandValue: 40,
      loyalty: 55, leadership: 42, entertainment: 48, mediaAbility: 84,
      fanConversion: 28, commercialAppeal: 30,
    }),
    style: { tone: 'PROVOCATIVE', platforms: ['TEXT', 'LONGFORM'], postingFrequency: 2 },
    bio: 'Reads the filings nobody reads and publishes what is in them. Has broken three stories that clubs would have preferred stayed unbroken and been threatened with legal action after all three. Not one has actually been brought.',
    avatarSeed: 'mira-sekulic-01',
  },
  {
    id: 'creator_teo_rivas',
    handle: 'teorivas',
    displayName: 'Teo Rivas',
    roles: ['OWNER', 'CLUB_PERSONALITY'],
    tier: 'RISING',
    followers: 128_000,
    attributes: ca({
      audience: 32, engagement: 80, charisma: 64, controversy: 14, brandValue: 34,
      loyalty: 94, leadership: 72, entertainment: 54, mediaAbility: 58,
      fanConversion: 81, commercialAppeal: 36,
    }),
    style: { tone: 'WHOLESOME', platforms: ['STREAM', 'TEXT'], postingFrequency: 4 },
    clubTemplateId: 'club_saltpine_harbour',
    bio: 'Third generation at Saltpine, still lives four streets from the ground, still does the half-time raffle himself. His entire media strategy is filming the under-nines and it converts better than anything Aurelia has ever paid for.',
    avatarSeed: 'teo-rivas-01',
  },
  {
    id: 'creator_bram_osei',
    handle: 'bramtakes',
    displayName: 'Bram Osei',
    roles: ['OWNER'],
    tier: 'RISING',
    followers: 96_000,
    attributes: ca({
      audience: 28, engagement: 68, charisma: 56, controversy: 71, brandValue: 26,
      loyalty: 88, leadership: 66, entertainment: 62, mediaAbility: 44,
      fanConversion: 64, commercialAppeal: 24,
    }),
    style: { tone: 'DRAMATIC', platforms: ['TEXT', 'STREAM'], postingFrequency: 5 },
    clubTemplateId: 'club_cinderwick_town',
    bio: 'Chairs a volunteer committee holding a hundred-and-thirty-year-old club together with fundraisers and stubbornness. Every post is either a plea or a threat, and the supporters would run into traffic for him.',
    avatarSeed: 'bram-osei-01',
  },
  {
    id: 'creator_lark_bexley',
    handle: 'larkbexley',
    displayName: 'Lark Bexley',
    roles: ['OWNER'],
    tier: 'RISING',
    followers: 74_000,
    attributes: ca({
      audience: 24, engagement: 58, charisma: 44, controversy: 36, brandValue: 30,
      loyalty: 85, leadership: 69, entertainment: 32, mediaAbility: 62,
      fanConversion: 50, commercialAppeal: 28,
    }),
    style: { tone: 'ANALYTICAL', platforms: ['TEXT'], postingFrequency: 1 },
    clubTemplateId: 'club_verrow_wanderers',
    bio: 'Elected president of Verrow on a manifesto of changing nothing and has honoured it completely. Posts once a week, in full sentences, usually to correct somebody. The membership finds this reassuring; everyone else finds it maddening.',
    avatarSeed: 'lark-bexley-01',
  },

  /* -------------------------------------------------------------- LOCAL */
  {
    id: 'creator_silas_broz',
    handle: 'silasbroz',
    displayName: 'Silas Broz',
    roles: ['PUNDIT'],
    tier: 'LOCAL',
    followers: 47_000,
    attributes: ca({
      audience: 18, engagement: 72, charisma: 34, controversy: 94, brandValue: 16,
      loyalty: 30, leadership: 22, entertainment: 44, mediaAbility: 60,
      fanConversion: 14, commercialAppeal: 12,
    }),
    style: { tone: 'PROVOCATIVE', platforms: ['TEXT', 'SHORTFORM'], postingFrequency: 11 },
    bio: 'Has watched every match of this competition and enjoyed none of them. Posts within ninety seconds of a final whistle, always negative, occasionally devastatingly correct, and is quoted by exactly the people who claim not to read him.',
    avatarSeed: 'silas-broz-01',
  },
  {
    id: 'creator_wren_dallimore',
    handle: 'wrendallimore',
    displayName: 'Wren Dallimore',
    roles: ['CLUB_PERSONALITY'],
    tier: 'LOCAL',
    followers: 41_000,
    attributes: ca({
      audience: 16, engagement: 90, charisma: 74, controversy: 58, brandValue: 14,
      loyalty: 98, leadership: 76, entertainment: 88, mediaAbility: 30,
      fanConversion: 72, commercialAppeal: 18,
    }),
    style: { tone: 'HYPE', platforms: ['SHORTFORM', 'STREAM'], postingFrequency: 9 },
    clubTemplateId: 'club_larkspur_wolves',
    bio: 'Leads the Den from a step-ladder and has not sat down at a football match since 2011. Films the walk from the pub every single week. If the Wolves ever won anything the footage would be unusable and everyone knows it.',
    avatarSeed: 'wren-dallimore-01',
  },
  {
    id: 'creator_nkem_okafor',
    handle: 'nkemokafor',
    displayName: 'Nkem Okafor',
    roles: ['PLAYER', 'CLUB_PERSONALITY'],
    tier: 'LOCAL',
    followers: 34_000,
    attributes: ca({
      audience: 14, engagement: 86, charisma: 70, controversy: 12, brandValue: 20,
      loyalty: 91, leadership: 58, entertainment: 74, mediaAbility: 36,
      fanConversion: 66, commercialAppeal: 26,
    }),
    style: { tone: 'COMEDIC', platforms: ['SHORTFORM', 'LONGFORM'], postingFrequency: 4 },
    clubTemplateId: 'club_redmere_republic',
    playerTemplateId: 'player_nkem_okafor',
    bio: 'Plays centre back for Redmere and posts about his allotment, in that order of skill. The tomatoes have a bigger following than the tackling. Signs every autograph and has never once been photographed looking anything but delighted.',
    avatarSeed: 'nkem-okafor-01',
  },
  {
    id: 'creator_juno_tikkanen',
    handle: 'junotikkanen',
    displayName: 'Juno Tikkanen',
    roles: ['INFLUENCER'],
    tier: 'LOCAL',
    followers: 28_000,
    attributes: ca({
      audience: 12, engagement: 81, charisma: 66, controversy: 48, brandValue: 15,
      loyalty: 40, leadership: 20, entertainment: 92, mediaAbility: 54,
      fanConversion: 22, commercialAppeal: 20,
    }),
    style: { tone: 'COMEDIC', platforms: ['SHORTFORM', 'TEXT'], postingFrequency: 10 },
    bio: 'Runs a parody tactics account that draws increasingly deranged arrows over screenshots. Two managers have used one of the diagrams in a real team meeting, which Juno has never let anyone forget.',
    avatarSeed: 'juno-tikkanen-01',
  },
  {
    id: 'creator_otto_grimshaw',
    handle: 'ottogrimshaw',
    displayName: 'Otto Grimshaw',
    roles: ['OWNER'],
    tier: 'LOCAL',
    followers: 22_000,
    attributes: ca({
      audience: 10, engagement: 62, charisma: 60, controversy: 68, brandValue: 18,
      loyalty: 99, leadership: 74, entertainment: 66, mediaAbility: 28,
      fanConversion: 58, commercialAppeal: 16,
    }),
    style: { tone: 'DRAMATIC', platforms: ['TEXT'], postingFrequency: 3 },
    clubTemplateId: 'club_ironhollow_forge',
    bio: 'Runs a pub two hundred metres from the Foundry Yard and, since a supporters\' buyout nobody expected to work, the football club as well. Has turned down two takeovers on principle and one because the number was insulting.',
    avatarSeed: 'otto-grimshaw-01',
  },
  {
    id: 'creator_halvor_skov',
    handle: 'halvorskov',
    displayName: 'Halvor Skov',
    roles: ['CLUB_PERSONALITY', 'PUNDIT'],
    tier: 'LOCAL',
    followers: 12_000,
    attributes: ca({
      audience: 8, engagement: 74, charisma: 46, controversy: 16, brandValue: 12,
      loyalty: 95, leadership: 40, entertainment: 38, mediaAbility: 68,
      fanConversion: 54, commercialAppeal: 10,
    }),
    style: { tone: 'WHOLESOME', platforms: ['TEXT', 'LONGFORM'], postingFrequency: 2 },
    clubTemplateId: 'club_verrow_wanderers',
    bio: 'Has edited the Verrow matchday programme since 1994 and reluctantly started publishing it online in 2023. Writes eight hundred words a week about a club that changes nothing, and somehow it is the best thing anyone writes about this league.',
    avatarSeed: 'halvor-skov-01',
  },
];

export const BASE_CREATOR_IDS: readonly string[] = BASE_CREATORS.map((c) => c.id);
