import { MENTAL_KEYS, type MentalKey } from '../../../players/mental';
import type { PlayerTemplate } from '../../schema';
import { attributesForOverall } from '../../generators/profiles';

/**
 * Named players.
 *
 * Most of a save's squads are generated — that is the point of the generator —
 * but a league needs a handful of people the world already has opinions about
 * on day one. These sixteen are the ones the media engine can reach for
 * immediately: the best player in the competition, the keeper everyone wants,
 * the nineteen-year-old whose follower count is outgrowing his appearance
 * count, and the thirty-five-year-old holding a relegation candidate together.
 *
 * Attributes are solved from a stated overall rather than hand-typed, so a
 * rebalance of the position weights cannot silently turn a star into a squad
 * player. All fictional; no template refers to any real footballer.
 */

const mn = (partial: Partial<Record<MentalKey, number>>): Record<string, number> =>
  Object.fromEntries(MENTAL_KEYS.map((k) => [k, partial[k] ?? 50]));

export const BASE_PLAYERS: readonly PlayerTemplate[] = [
  {
    id: 'player_dario_leone',
    firstName: 'Dario', lastName: 'Leone', age: 28, nationality: 'TBR',
    position: 'ST', secondaryPositions: ['CAM'], footedness: 'left', height: 184,
    attributes: attributesForOverall('ST', 89, { finishing: 94, composure: 92, pace: 84 }),
    mental: mn({ confidence: 88, morale: 72, discipline: 62, leadership: 74, ambition: 86,
      consistency: 83, pressureHandling: 90, professionalism: 80, loyalty: 44, temperament: 58 }),
    traitIds: ['natural_finisher', 'big_game', 'showman'],
    potential: 91,
    clubTemplateId: 'club_marrowgate_athletic',
    portraitSeed: 'dario-leone',
  },
  {
    id: 'player_arvid_kjaer',
    firstName: 'Arvid', lastName: 'Kjaer', age: 30, nationality: 'NHV',
    position: 'GK', footedness: 'right', height: 194,
    attributes: attributesForOverall('GK', 85, { reflexes: 91, composure: 84, positioning: 86 }),
    mental: mn({ confidence: 74, morale: 68, discipline: 84, leadership: 82, ambition: 55,
      consistency: 88, pressureHandling: 86, professionalism: 90, loyalty: 76, temperament: 80 }),
    traitIds: ['wall', 'leader'],
    potential: 86,
    clubTemplateId: 'club_marrowgate_athletic',
    portraitSeed: 'arvid-kjaer',
  },
  {
    id: 'player_rem_bassey',
    firstName: 'Rem', lastName: 'Bassey', age: 24, nationality: 'VLK',
    position: 'RW', secondaryPositions: ['LW', 'ST'], footedness: 'left', height: 176,
    attributes: attributesForOverall('RW', 81, { dribbling: 89, acceleration: 88, crossing: 72 }),
    mental: mn({ confidence: 92, morale: 78, discipline: 41, leadership: 44, ambition: 84,
      consistency: 58, pressureHandling: 66, professionalism: 48, loyalty: 46, temperament: 38 }),
    traitIds: ['showman', 'speedster', 'hot_head'],
    potential: 86,
    clubTemplateId: 'club_neon_row_fc',
    creatorTemplateId: 'creator_rem_bassey',
    portraitSeed: 'rem-bassey',
  },
  {
    id: 'player_kacper_wojcik',
    firstName: 'Kacper', lastName: 'Wojcik', age: 26, nationality: 'PAL',
    position: 'ST', secondaryPositions: ['LW'], footedness: 'right', height: 181,
    attributes: attributesForOverall('ST', 80, { finishing: 86, positioning: 82 }),
    mental: mn({ confidence: 76, morale: 74, discipline: 70, leadership: 52, ambition: 68,
      consistency: 74, pressureHandling: 71, professionalism: 82, loyalty: 60, temperament: 72 }),
    traitIds: ['natural_finisher', 'team_player'],
    potential: 83,
    clubTemplateId: 'club_aurelia_sc',
    creatorTemplateId: 'creator_kacper_wojcik',
    portraitSeed: 'kacper-wojcik',
  },
  {
    id: 'player_fen_duvall',
    firstName: 'Fen', lastName: 'Duvall', age: 19, nationality: 'VLK',
    position: 'CAM', secondaryPositions: ['CM', 'LW'], footedness: 'right', height: 174,
    attributes: attributesForOverall('CAM', 68, { vision: 76, technique: 78, dribbling: 74 }),
    mental: mn({ confidence: 70, morale: 82, discipline: 58, leadership: 34, ambition: 88,
      consistency: 44, pressureHandling: 42, professionalism: 66, loyalty: 48, temperament: 54 }),
    traitIds: ['wonderkid', 'press_resistant'],
    potential: 89,
    clubTemplateId: 'club_duskford_rovers',
    creatorTemplateId: 'creator_fen_duvall',
    portraitSeed: 'fen-duvall',
  },
  {
    id: 'player_nkem_okafor',
    firstName: 'Nkem', lastName: 'Okafor', age: 27, nationality: 'NKA',
    position: 'CB', secondaryPositions: ['CDM'], footedness: 'right', height: 190,
    attributes: attributesForOverall('CB', 70, { defending: 76, strength: 82 }),
    mental: mn({ confidence: 62, morale: 88, discipline: 86, leadership: 68, ambition: 38,
      consistency: 76, pressureHandling: 64, professionalism: 84, loyalty: 94, temperament: 88 }),
    traitIds: ['aerial_threat', 'cult_hero', 'team_player'],
    potential: 72,
    clubTemplateId: 'club_redmere_republic',
    creatorTemplateId: 'creator_nkem_okafor',
    portraitSeed: 'nkem-okafor',
  },
  {
    id: 'player_hugo_ravenscroft',
    firstName: 'Hugo', lastName: 'Ravenscroft', age: 31, nationality: 'VLK',
    position: 'CB', secondaryPositions: ['CDM'], footedness: 'right', height: 189,
    attributes: attributesForOverall('CB', 79, { defending: 86, positioning: 84, strength: 85 }),
    mental: mn({ confidence: 78, morale: 66, discipline: 34, leadership: 90, ambition: 52,
      consistency: 72, pressureHandling: 84, professionalism: 68, loyalty: 88, temperament: 36 }),
    traitIds: ['leader', 'hot_head', 'veteran'],
    potential: 80,
    clubTemplateId: 'club_ironhollow_forge',
    portraitSeed: 'hugo-ravenscroft',
  },
  {
    id: 'player_selim_yalcin',
    firstName: 'Selim', lastName: 'Yalcin', age: 34, nationality: 'AKR',
    position: 'CM', secondaryPositions: ['CDM', 'CAM'], footedness: 'left', height: 178,
    attributes: attributesForOverall('CM', 77, { passing: 88, vision: 86, stamina: 58 }),
    mental: mn({ confidence: 72, morale: 64, discipline: 78, leadership: 86, ambition: 40,
      consistency: 84, pressureHandling: 88, professionalism: 92, loyalty: 82, temperament: 76 }),
    traitIds: ['playmaker', 'veteran'],
    potential: 77,
    clubTemplateId: 'club_verrow_wanderers',
    portraitSeed: 'selim-yalcin',
  },
  {
    id: 'player_marek_dobrev',
    firstName: 'Marek', lastName: 'Dobrev', age: 25, nationality: 'DRA',
    position: 'CDM', secondaryPositions: ['CM', 'CB'], footedness: 'right', height: 185,
    attributes: attributesForOverall('CDM', 78, { defending: 84, stamina: 88, positioning: 83 }),
    mental: mn({ confidence: 64, morale: 70, discipline: 82, leadership: 58, ambition: 60,
      consistency: 86, pressureHandling: 74, professionalism: 90, loyalty: 66, temperament: 78 }),
    traitIds: ['workhorse', 'team_player'],
    potential: 83,
    clubTemplateId: 'club_vantage_point_fc',
    portraitSeed: 'marek-dobrev',
  },
  {
    id: 'player_ravi_prakash',
    firstName: 'Ravi', lastName: 'Prakash', age: 27, nationality: 'SUN',
    position: 'GK', footedness: 'right', height: 188,
    attributes: attributesForOverall('GK', 77, { passing: 74, reflexes: 79 }),
    mental: mn({ confidence: 70, morale: 72, discipline: 74, leadership: 56, ambition: 66,
      consistency: 68, pressureHandling: 62, professionalism: 86, loyalty: 58, temperament: 70 }),
    traitIds: ['sweeper_keeper'],
    potential: 80,
    clubTemplateId: 'club_vantage_point_fc',
    portraitSeed: 'ravi-prakash',
  },
  {
    id: 'player_ciro_pastore',
    firstName: 'Ciro', lastName: 'Pastore', age: 23, nationality: 'MRD',
    position: 'LW', secondaryPositions: ['RW', 'CAM'], footedness: 'right', height: 172,
    attributes: attributesForOverall('LW', 75, { dribbling: 86, pace: 88, acceleration: 89 }),
    mental: mn({ confidence: 84, morale: 76, discipline: 48, leadership: 30, ambition: 78,
      consistency: 46, pressureHandling: 52, professionalism: 44, loyalty: 54, temperament: 42 }),
    traitIds: ['speedster', 'showman', 'glass_confidence'],
    potential: 84,
    clubTemplateId: 'club_larkspur_wolves',
    portraitSeed: 'ciro-pastore',
  },
  {
    id: 'player_oskar_lindqvist',
    firstName: 'Oskar', lastName: 'Lindqvist', age: 33, nationality: 'OST',
    position: 'ST', secondaryPositions: ['CAM'], footedness: 'right', height: 186,
    attributes: attributesForOverall('ST', 71, { finishing: 80, composure: 82, pace: 54 }),
    mental: mn({ confidence: 74, morale: 80, discipline: 72, leadership: 84, ambition: 30,
      consistency: 70, pressureHandling: 82, professionalism: 78, loyalty: 96, temperament: 84 }),
    traitIds: ['cult_hero', 'veteran', 'leader'],
    potential: 71,
    clubTemplateId: 'club_saltpine_harbour',
    portraitSeed: 'oskar-lindqvist',
  },
  {
    id: 'player_amari_conteh',
    firstName: 'Amari', lastName: 'Conteh', age: 20, nationality: 'ZAM',
    position: 'LB', secondaryPositions: ['LW'], footedness: 'left', height: 177,
    attributes: attributesForOverall('LB', 68, { pace: 84, stamina: 82, crossing: 72 }),
    mental: mn({ confidence: 62, morale: 78, discipline: 64, leadership: 36, ambition: 74,
      consistency: 50, pressureHandling: 46, professionalism: 72, loyalty: 62, temperament: 60 }),
    traitIds: ['speedster'],
    potential: 84,
    clubTemplateId: 'club_duskford_rovers',
    portraitSeed: 'amari-conteh',
  },
  {
    id: 'player_bilal_haddad',
    firstName: 'Bilal', lastName: 'Haddad', age: 22, nationality: 'KRS',
    position: 'CAM', secondaryPositions: ['CM'], footedness: 'both', height: 179,
    attributes: attributesForOverall('CAM', 77, { vision: 85, technique: 86, passing: 84 }),
    mental: mn({ confidence: 80, morale: 70, discipline: 60, leadership: 46, ambition: 90,
      consistency: 58, pressureHandling: 60, professionalism: 62, loyalty: 32, temperament: 52 }),
    traitIds: ['playmaker', 'press_resistant', 'mercenary'],
    potential: 90,
    clubTemplateId: 'club_aurelia_sc',
    portraitSeed: 'bilal-haddad',
  },
  {
    id: 'player_tavish_mowbray',
    firstName: 'Tavish', lastName: 'Mowbray', age: 35, nationality: 'VLK',
    position: 'CB', footedness: 'right', height: 187,
    attributes: attributesForOverall('CB', 64, { defending: 74, positioning: 80, pace: 42 }),
    mental: mn({ confidence: 66, morale: 62, discipline: 80, leadership: 94, ambition: 22,
      consistency: 74, pressureHandling: 86, professionalism: 88, loyalty: 98, temperament: 82 }),
    traitIds: ['veteran', 'leader', 'cult_hero'],
    potential: 64,
    clubTemplateId: 'club_cinderwick_town',
    portraitSeed: 'tavish-mowbray',
  },
  {
    id: 'player_elias_falk',
    firstName: 'Elias', lastName: 'Falk', age: 21, nationality: 'ELD',
    position: 'RW', secondaryPositions: ['ST'], footedness: 'left', height: 175,
    attributes: attributesForOverall('RW', 70, { dribbling: 79, technique: 76 }),
    mental: mn({ confidence: 68, morale: 84, discipline: 66, leadership: 40, ambition: 72,
      consistency: 52, pressureHandling: 50, professionalism: 74, loyalty: 70, temperament: 64 }),
    traitIds: ['late_bloomer'],
    potential: 85,
    clubTemplateId: 'club_ember_nine',
    portraitSeed: 'elias-falk',
  },
];

export const BASE_PLAYER_IDS: readonly string[] = BASE_PLAYERS.map((p) => p.id);
