"""Reproducible raster sizing only; creative edits belong to image generation.
Run after adding a controlled generation to premium-jobs.json.
"""
import hashlib, json
from pathlib import Path
from PIL import Image, ImageOps

ROOT = Path(__file__).resolve().parents[2]
DEST = ROOT / 'apps/game/public/art/premium'
DEST.mkdir(parents=True, exist_ok=True)
jobs = json.loads((Path(__file__).parent / 'premium-jobs.json').read_text(encoding='utf-8'))
records = []
manifest_path = ROOT / 'apps/game/src/design/art/premium-assets.json'
previous = {r['key']: r for r in json.loads(manifest_path.read_text(encoding='utf-8'))} if manifest_path.exists() else {}
for job in jobs:
    src = Path(job['source'])
    if not src.exists():
        raise FileNotFoundError(src)
    with Image.open(src) as image:
        if 'sourceRegion' in job:
            x, y, w, h = job['sourceRegion']
            image = image.crop((round(x*image.width), round(y*image.height), round((x+w)*image.width), round((y+h)*image.height)))
        portrait = job['kind'] == 'character'
        isolated = job['kind'] in ('crest', 'object', 'kit', 'trophy')
        sizes = {'hero': (640, 960) if portrait else (640, 640) if isolated else (1200, 800), 'card': (240, 320) if portrait else (320, 320) if isolated else (480, 320), 'thumb': (96, 96) if portrait or isolated else (240, 160)}
        variants = {}
        for variant, size in sizes.items():
            target = DEST / (job['name'] + '-' + variant + '.webp')
            variant_image = image
            crop_region = job.get('cropRegions', {}).get(variant)
            if crop_region:
                x, y, w, h = crop_region
                variant_image = image.crop((round(x*image.width), round(y*image.height), round((x+w)*image.width), round((y+h)*image.height)))
            # Upper portrait crop retains the face. Environment crops are centred.
            wrong_size = target.exists() and Image.open(target).size != size
            old = previous.get(job['key'], {})
            recropped = any(old.get(key) != job.get(key) for key in ('source', 'sourceRegion', 'cropRegions'))
            if not target.exists() or wrong_size or recropped or target.stat().st_mtime < src.stat().st_mtime:
                crop = ImageOps.fit(variant_image.convert('RGB'), size, Image.Resampling.LANCZOS, centering=(0.5, 0.18 if portrait else 0.5))
                crop.save(target, 'WEBP', quality=82 if variant == 'hero' else 78, method=6)
            variants[variant] = {'src': '/art/premium/' + target.name, 'width': size[0], 'height': size[1], 'bytes': target.stat().st_size, 'sha256': hashlib.sha256(target.read_bytes()).hexdigest()}
        records.append({**job, 'sourceSha256': hashlib.sha256(src.read_bytes()).hexdigest(), 'generator': 'OpenAI image_gen', 'provenance': 'Original fictional generated artwork; user-directed production. No third-party brands or likenesses requested.', 'runtime3D': False, 'crop': 'upper-centre' if portrait else 'centre', 'fallback': 'Code-native gradient / existing deterministic SVG', 'variants': variants})
(ROOT / 'apps/game/src/design/art/premium-assets.json').write_text(json.dumps(records, indent=2) + '\n', encoding='utf-8')
index = {r['key']: {'kind': r['kind'], 'variants': {name: {'src': v['src']} for name, v in r['variants'].items()}} for r in records}
(ROOT / 'apps/game/src/design/art/premium-index.ts').write_text('// Generated by tools/brand/optimise-premium.py. Prompts and provenance: premium-assets.json.\nexport const PREMIUM_ASSETS = ' + json.dumps(index, indent=2) + ' as const;\nexport type AssetKey = keyof typeof PREMIUM_ASSETS;\n', encoding='utf-8')
print(f'Optimised {len(records)} art assets; {sum(v["bytes"] for r in records for v in r["variants"].values()):,} bytes across all crops')
